/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/salud": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Estado del back, de Ollama y del modelo (+ pin de versión) */
        get: operations["salud"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/estructura/{tipo_doc}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Secciones esperadas (en orden canónico) de un tipo de documento */
        get: operations["estructura"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analizar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analiza un texto y devuelve sugerencias trazables a los 9 indicadores */
        post: operations["analizar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/secciones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Detecta las secciones del documento (índice) para analizar por partes */
        post: operations["secciones"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reescribir": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reescribe un fragmento en registro académico formal (RF-09 on-demand) */
        post: operations["reescribir"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat tutor pedagógico (andamiaje: guía, no escribe por el alumno) */
        post: operations["chat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/detectar-parametros": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Detecta tipo de documento, normativa y carrera (onboarding del Wizard) */
        post: operations["detectarParametros"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalizarRequest */
        AnalizarRequest: {
            /** Texto */
            texto: string;
            /**
             * Tipo Doc
             * @default ensayo_argumentativo
             */
            tipo_doc: string;
            /** Dimensiones */
            dimensiones?: components["schemas"]["Dimension"][] | null;
            /** Seed */
            seed?: number | null;
            /** Alcance */
            alcance?: string | null;
            /** Offset Base */
            offset_base?: number | null;
        };
        /** AnalizarResponse */
        AnalizarResponse: {
            /** Sugerencias */
            sugerencias: components["schemas"]["Sugerencia"][];
            /**
             * Parcial
             * @default false
             */
            parcial: boolean;
            /**
             * Motores Ok
             * @default []
             */
            motores_ok: string[];
            /**
             * Motores Fallidos
             * @default []
             */
            motores_fallidos: string[];
            /** Nota */
            nota?: string | null;
        };
        /** ChatRequest */
        ChatRequest: {
            /** Mensaje */
            mensaje: string;
            /** Historial */
            historial?: components["schemas"]["MensajeChat"][] | null;
            contexto?: components["schemas"]["ContextoChat"] | null;
        };
        /** ChatResponse */
        ChatResponse: {
            /** Respuesta */
            respuesta: string;
        };
        /** ContextoChat */
        ContextoChat: {
            /** Documento */
            documento?: string | null;
            /** Sugerencia Id */
            sugerencia_id?: string | null;
            /** Tipo Chat */
            tipo_chat?: string | null;
        };
        /** DetectarParametrosRequest */
        DetectarParametrosRequest: {
            /** Texto */
            texto: string;
        };
        /** DetectarParametrosResponse */
        DetectarParametrosResponse: {
            /** Tipo Doc */
            tipo_doc?: string | null;
            /** Normativa */
            normativa?: string | null;
            /** Carrera */
            carrera?: string | null;
            /** Confianza Tipo Doc */
            confianza_tipo_doc?: number | null;
            /** Confianza Normativa */
            confianza_normativa?: number | null;
            /** Confianza Carrera */
            confianza_carrera?: number | null;
        };
        /**
         * Dimension
         * @enum {string}
         */
        Dimension: "organizacion" | "coherencia" | "gramatica";
        /** EstructuraResponse */
        EstructuraResponse: {
            /** Tipo Doc */
            tipo_doc: string;
            /** Secciones */
            secciones: components["schemas"]["SeccionEsperada"][];
        };
        /**
         * Fuente
         * @enum {string}
         */
        Fuente: "reglas" | "pln" | "modelo";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MensajeChat */
        MensajeChat: {
            /** Rol */
            rol: string;
            /** Contenido */
            contenido: string;
        };
        /**
         * Nivel
         * @enum {string}
         */
        Nivel: "palabra" | "oracion" | "parrafo" | "documento";
        /**
         * Rango
         * @description Índices de carácter sobre EXACTAMENTE el texto recibido (normalizado NFC).
         */
        Rango: {
            /** Inicio */
            inicio: number;
            /** Fin */
            fin: number;
        };
        /** ReescribirRequest */
        ReescribirRequest: {
            /** Fragmento */
            fragmento: string;
            /**
             * Motivo
             * @default uso no académico
             */
            motivo: string;
            /** Seed */
            seed?: number | null;
        };
        /** ReescribirResponse */
        ReescribirResponse: {
            /** Reescritura Formal */
            reescritura_formal: string;
            /** Nota */
            nota: string;
        };
        /** SaludResponse */
        SaludResponse: {
            /** Estado */
            estado: string;
            /** Modelo Listo */
            modelo_listo: boolean;
            /** Ollama Ok */
            ollama_ok: boolean;
            /** Reglas Listas */
            reglas_listas: boolean;
            /** Version */
            version: string;
            /** Ollama Version */
            ollama_version?: string | null;
            /** Modelo Digest */
            modelo_digest?: string | null;
            /**
             * Pin Ok
             * @default true
             */
            pin_ok: boolean;
        };
        /** SeccionEsperada */
        SeccionEsperada: {
            /** Nombre */
            nombre: string;
            /** Orden */
            orden: number;
            /**
             * Recomendada
             * @default false
             */
            recomendada: boolean;
        };
        /**
         * SeccionInfo
         * @description Una sección detectada por su título, con rango de carácter sobre el texto NFC.
         */
        SeccionInfo: {
            /** Idx */
            idx: number;
            /** Titulo */
            titulo: string;
            /** Inicio */
            inicio: number;
            /** Fin */
            fin: number;
            /** N Palabras */
            n_palabras: number;
        };
        /** SeccionesRequest */
        SeccionesRequest: {
            /** Texto */
            texto: string;
        };
        /** SeccionesResponse */
        SeccionesResponse: {
            /** Secciones */
            secciones: components["schemas"]["SeccionInfo"][];
        };
        /**
         * Severidad
         * @enum {string}
         */
        Severidad: "error" | "advertencia" | "sugerencia";
        /** Sugerencia */
        Sugerencia: {
            /**
             * Id
             * @default
             */
            id: string;
            /** Rf */
            rf: string;
            dimension: components["schemas"]["Dimension"];
            severidad: components["schemas"]["Severidad"];
            nivel: components["schemas"]["Nivel"];
            rango?: components["schemas"]["Rango"] | null;
            /** Mensaje */
            mensaje: string;
            /** Sugerencia */
            sugerencia?: string | null;
            fuente: components["schemas"]["Fuente"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    salud: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaludResponse"];
                };
            };
        };
    };
    estructura: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tipo_doc: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EstructuraResponse"];
                };
            };
            /** @description tipo_doc desconocido */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analizar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalizarRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalizarResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    secciones: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SeccionesRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeccionesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reescribir: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReescribirRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReescribirResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description El modelo no está disponible */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    chat: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    detectarParametros: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DetectarParametrosRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetectarParametrosResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
